# Параметры тренировки
lr0: 0.01               # Начальная скорость обучения
lrf: 0.01               # Конечная скорость обучения
momentum: 0.937         # Momentum SGD/Adam beta1
weight_decay: 0.0005    # L2-регуляризация (веса)
warmup_epochs: 3.0      # Эпохи прогрева
warmup_momentum: 0.8    # Начальный момент на этапе прогрева
warmup_bias_lr: 0.1     # Начальная скорость обучения bias во время прогрева

# Коэффициенты функции потерь
box: 7.5                # Усиление потери бокса
cls: 0.5                # Усиление потери класса
dfl: 1.5                # Усиление потери распределения фокальной длины
kobj: 1.0               # Коэффициент усиления для объектов (замена параметру obj)

# Аугментации
hsv_h: 0.015            # HSV оттенок
hsv_s: 0.7              # HSV насыщенность
hsv_v: 0.4              # HSV яркость
degrees: 0.3            # Угол поворота
translate: 0.3         # Смещение
scale: 0.5              # Масштабирование
shear: 0.5              # Сдвиг
perspective: 0.3        # Перспективные искажения
flipud: 0.5             # Вертикальный разворот
fliplr: 0.5             # Горизонтальный разворот
mosaic: 1.0             # Мозаичная аугментация
mixup: 0.7              # Mixup аугментация

# Размер данных и батча
imgsz: 640              # Размер изображений
batch: 18               # Размер батча
epochs: 120             # Количество эпох

# Устройство
device: 'cuda'               # Используемое устройство (0 для CUDA)

# # Параметры тренировки
# lr0: 0.01               # Начальная скорость обучения
# lrf: 0.01               # Конечная скорость обучения
# momentum: 0.937         # Momentum SGD/Adam beta1
# weight_decay: 0.0005    # L2-регуляризация (веса)
# warmup_epochs: 3.0      # Эпохи прогрева
# warmup_momentum: 0.8    # Начальный момент на этапе прогрева
# warmup_bias_lr: 0.1     # Начальная скорость обучения bias во время прогрева

# # Коэффициенты функции потерь
# box: 7.5                # Усиление потери бокса
# cls: 0.5                # Усиление потери класса
# dfl: 1.5                # Усиление потери распределения фокальной длины
# kobj: 1.0               # Коэффициент усиления для объектов (замена параметру obj)

# # Аугментации
# hsv_h: 0.015            # HSV оттенок
# hsv_s: 0.7              # HSV насыщенность
# hsv_v: 0.4              # HSV яркость
# degrees: 0.1            # Угол поворота
# translate: 0.1          # Смещение
# scale: 0.5              # Масштабирование
# shear: 0.0              # Сдвиг
# perspective: 0.3        # Перспективные искажения
# flipud: 0.0             # Вертикальный разворот
# fliplr: 0.5             # Горизонтальный разворот
# mosaic: 1.0             # Мозаичная аугментация
# mixup: 0.5              # Mixup аугментация

# # Размер данных и батча
# imgsz: 640              # Размер изображений
# batch: 18               # Размер батча
# epochs: 100             # Количество эпох

# # Устройство
# device: 0               # Используемое устройство (0 для CUDA)
